# Generated by Django 6.0.5 on 2026-05-31 09:34

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.events_upload_to, verbose_name='Cover image'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='Event date'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Location'),
        ),
    ]
