# Generated by Django 5.2.1 on 2025-07-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='Event slug'),
        ),
    ]
