# Generated by Django 6.0.5 on 2026-06-06 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_upload_to_slugify'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='album',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='gallery.album', verbose_name='Gallery album'),
        ),
    ]
