# Generated by Django 5.2.1 on 2025-07-08 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_events_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='EventsCategory',
            new_name='EventCategory',
        ),
        migrations.RenameModel(
            old_name='EventsCategoryTranslation',
            new_name='EventCategoryTranslation',
        ),
        migrations.RenameModel(
            old_name='EventsImage',
            new_name='EventImage',
        ),
        migrations.RenameModel(
            old_name='EventsTranslation',
            new_name='EventTranslation',
        ),
        migrations.AlterModelTable(
            name='event',
            table='Event',
        ),
        migrations.AlterModelTable(
            name='eventcategory',
            table='EventCategory',
        ),
        migrations.AlterModelTable(
            name='eventcategorytranslation',
            table='EventCategory_translation',
        ),
        migrations.AlterModelTable(
            name='eventimage',
            table='EventImage',
        ),
        migrations.AlterModelTable(
            name='eventtranslation',
            table='Event_translation',
        ),
    ]
