# Generated by Django 5.2.1 on 2025-07-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_events_event_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_at'], name='Event_created_ef363d_idx'),
        ),
    ]
