openapi: 3.0.0
info:
  version: 1.0.0
  title: NNIKITI API
  description: This is an API for the educational institution's information system.

servers:
  - url: http://127.0.0.1:8000/api/v1/
    description: Local development

tags:
  - name: auth
    description: Auth endpoints
  - name: core
    description: Core endpoints

paths: 
  /core/main-slider-item/:
    get:
      tags:
        - core
      description: Returns a list of slider images
      responses:
        '200':
          description: Successfully returned a list of slider images
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MainSliderItem'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /core/statistic-block/:
    get:
      tags:
        - core
      description: Returns a list of data for statistic block
      responses:
        '200':
          description: Successfully returned a list of data for statictic block
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StatisticBlock'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /auth/login/google-oauth2/:
    get:
      tags:
        - auth
      description: Starts the OAuth2 flow for Google authorization.
                    The user will be redirected to the Google login page.
                    After authorization, the user will be redirected to the callback URL, 
                    where the access token will be processed.
      responses:
        '302':
          description: Redirect to Google OAuth2 consent screen
          headers:
            Location:
              description: Google OAuth2 consent screen URL
              schema:
                type: string
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  
  /auth/logout/:
    post:
      tags:
        - auth
      description: Logs out the user. Requires `refresh_token` cookie
      security:
       - JWTAuthCookies: []
      requestBody:
        description: No body required; cookie is used
        required: false
        content:
          application/json:
            schema:
              type: object
      responses:
        '204':
          description: No content (logout successful).
        '400':
          description: Invalid token or refresh token not provided.
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    
  /auth/token/refresh/:
    post:
      tags:
        - auth
      description: Refreshes the access token by taking the refresh token from the `refresh_token` cookie
      security:
        - JWTAuthCookies: []
      requestBody:
        description: No body required; cookie is used
        required: false
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Token successfully updated.
          headers:
            Set-Cookie:
              description: A new access token in a cookie named `access_token`.
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
        '401':
          description: Unauthorized - no valid refresh token
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
components:
  securitySchemes:
    JWTAuthCookies:
      type: apiKey
      in: cookie
      name: access_token

  schemas:
    MainSliderItem:
      type: object
      properties:
        id:
          title: ID
          type: integer
          readOnly: true
        image: 
          title: Image
          type: string
          format: uri
          readOnly: true
    StatisticBlock:
      type: object
      properties:
        id:
          title: ID
          type: integer
          readOnly: true
        title:
          title: Title
          type: string
          readOnly: True
        description:
          title: Description
          type: string
          readOnly: True
        start_value:
          title: Start Value
          type: integer
          readOnly: True
      
          
          
          
          
        