openapi: 3.0.0
info:
  version: 1.0.0
  title: NNIKITI API
  description: This is an API for the educational institution's information system.

servers:
  - url: http://127.0.0.1:8000/api/v1/
    description: Local development

tags:
  - name: users
    description: Users endpoints
  - name: core
    description: Core endpoints
  - name: events
    description: Events endpoints

paths:
  /core/main-slider-item/:
    get:
      tags:
        - core
      description: Returns a list of slider images
      responses:
        "200":
          description: Successfully returned a list of slider images
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MainSliderItem"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /core/statistic-block/:
    get:
      tags:
        - core
      description: Returns a list of data for statistic block
      responses:
        "200":
          description: Successfully returned a list of data for statictic block
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/StatisticBlock"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /core/partners/:
    get:
      tags:
        - core
      description: Returns a list of data for partners block
      responses:
        "200":
          description: Successfully returned a list of data for partners block
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Partners"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /users/login/google-oauth2/:
    get:
      tags:
        - users
      description: Starts the OAuth2 flow for Google authorization.
        The user will be redirected to the Google login page.
        After authorization, the user will be redirected to the callback URL,
        where the access token will be processed.
      responses:
        "302":
          description: Redirect to Google OAuth2 consent screen
          headers:
            Location:
              description: Google OAuth2 consent screen URL
              schema:
                type: string
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /users/logout/:
    post:
      tags:
        - users
      description: Logs out the user. Requires `refresh_token` cookie
      security:
        - JWTAuthCookies: []
      requestBody:
        description: No body required; cookie is used
        required: false
        content:
          application/json:
            schema:
              type: object
      responses:
        "204":
          description: No content (logout successful).
        "400":
          description: Invalid token or refresh token not provided.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /users/me/:
    get:
      tags:
        - users
      description: Returns information about the current user. Requires `access_token` cookie
      security:
        - JWTAuthCookies: []
      responses:
        "200":
          description: Successfully returned a user information
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        "500":
          description: Failed to retrieve user profile
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /users/token/refresh/:
    post:
      tags:
        - users
      description: Refreshes the access token by taking the refresh token from the `refresh_token` cookie
      security:
        - JWTAuthCookies: []
      requestBody:
        description: No body required; cookie is used
        required: false
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Token successfully updated.
          headers:
            Set-Cookie:
              description: A new access token in a cookie named `access_token`.
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  access:
                    type: string
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
        "401":
          description: Unauthorized - no valid refresh token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
                type: object
                properties:
                  detail:
                    type: string
  /events/:
    get:
      tags:
        - events
      description: Returns list of the events.
      responses:
        "200":
          description: Event list successfully returned
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Events"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
components:
  securitySchemes:
    JWTAuthCookies:
      type: apiKey
      in: cookie
      name: access_token

  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
          description: Error code
        message:
          type: string
          description: Human readable error message
      required:
        - code
        - message

    MainSliderItem:
      type: object
      properties:
        id:
          title: ID
          type: integer
          readOnly: true
        image:
          title: Image
          type: string
          format: uri
          readOnly: true
    StatisticBlock:
      type: object
      properties:
        id:
          title: ID
          type: integer
          readOnly: true
        title:
          title: Title
          type: string
          readOnly: True
        description:
          title: Description
          type: string
          readOnly: True
        start_value:
          title: Start Value
          type: integer
          readOnly: True
        order:
          title: Order
          type: integer
          readOnly: True
    User:
      type: object
      properties:
        id:
          title: ID
          type: integer
          readOnly: true
        first_name:
          title: First name
          type: string
          readOnly: true
        last_name:
          title: Last name
          type: string
          readOnly: true
        email:
          title: Email
          type: string
          format: email
          readOnly: true
        avatar:
          title: Avatar
          type: string
          format: uri
          readOnly: true
    Events:
      type: object
      properties:
        id:
          title: ID
          type: integer
          readOnly: true
        title:
          title: Title
          type: string
          readOnly: true
        body:
          title: Body
          type: string
          readOnly: true
        body_html:
          title: HTML Body
          type: string
          readOnly: true
        category:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            rgb_color:
              type: string
              example: "(244,255,244,0.1)"
        created_at:
          type: string
          format: date-time
          example: "2025-06-30T11:39:01.957067Z"
          readOnly: true
        updated_at:
          type: string
          format: date-time
          example: "2025-06-30T12:10:46.028492Z"
          readOnly: true
    Partners:
      type: object
      properties:
        id:
          title: ID
          type: integer
          readOnly: true
        name:
          title: Name
          type: string
          readOnly: true
        image:
          title: Image
          type: string
          format: uri
          readOnly: true
        site_url:
          title: Site url
          type: string
          format: uri
          readOnly: true
