/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/google/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Вхід через Google OAuth2 (PKCE)
         * @description Приймає `code` та `code_verifier` з Google OAuth2 PKCE flow.
         *
         *     У відповіді повертає `access_token` у тілі. `refresh_token` встановлюється як **HttpOnly cookie** автоматично — фронтенд його не бачить.
         *
         *     Домен обмежений: тільки `@nuwm.edu.ua` пошти.
         */
        post: operations["v1_auth_google_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Оновлення access token
         * @description Оновлює `access_token` використовуючи `refresh_token` з HttpOnly cookie.
         *
         *     Фронтенд надсилає тільки `grant_type` і `client_id` — cookie з `refresh_token` браузер підставляє автоматично.
         */
        post: operations["v1_auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/alumni/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET: Returns a list of all Alumni.
         *     POST: Create a new Alumnus (Ukrainian translation only) */
        get: operations["v1_core_alumni_retrieve"];
        put?: never;
        /** @description GET: Returns a list of all Alumni.
         *     POST: Create a new Alumnus (Ukrainian translation only) */
        post: operations["v1_core_alumni_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/alumni-slider-items/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns a list of all AlumniSlider. */
        get: operations["v1_core_alumni_slider_items_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/alumni/years/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список років випуску
         * @description Повертає унікальні роки випуску у спадному порядку. Використовується для фільтрації випускників.
         */
        get: operations["v1_core_alumni_years_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/educational-programs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ListAPIView for EducationalProgram. */
        get: operations["v1_core_educational_programs_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/faq/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns a list of all FAQ items. */
        get: operations["v1_core_faq_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/main-slider-items/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns a list of all images in the main slider. */
        get: operations["v1_core_main_slider_items_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/partners/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns a list of all images in the partners. */
        get: operations["v1_core_partners_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/statistic-block/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns a list of all data in the statistic block */
        get: operations["v1_core_statistic_block_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ListAPIView for Department. */
        get: operations["v1_departments_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description RetrieveAPIView for Department. */
        get: operations["v1_departments_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description API view to retrieve a list of published events. */
        get: operations["v1_events_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description API view to retrieve a single published event by its ID. */
        get: operations["v1_events_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Профіль поточного користувача
         * @description Потребує `Authorization: Bearer <access_token>`.
         */
        get: operations["v1_users_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/role/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Роль поточного користувача
         * @description Публічний ендпоінт. Для неавторизованих повертає роль `GU` (Guest).
         *
         *     | Роль | Код |
         *     |------|-----|
         *     | Admin | `AD` |
         *     | Teacher | `TE` |
         *     | Student | `ST` |
         *     | Data Operator | `DO` |
         *     | Guest | `GU` |
         */
        get: operations["v1_users_role_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Serializer for the AlumniSlider model. */
        AlumniSlider: {
            readonly id: number;
            /** Format: uri */
            image: string;
        };
        /** @description Serializer for CategorizedTag. */
        CategorizedTag: {
            readonly id: number;
            readonly name: string;
        };
        /** @description Serializer for DepartmentDetail. */
        DepartmentDetail: {
            readonly id: number;
            readonly name: string;
            readonly description: string;
            readonly address: string;
            /**
             * Електронна адреса
             * Format: email
             */
            email: string;
            readonly head_of_department: components["schemas"]["HeadOfDepartment"][];
            readonly educational_program: components["schemas"]["DepartmentEducationalProgram"][];
            readonly team: components["schemas"]["FacultyMember"][];
            readonly history: components["schemas"]["DepartmentHistory"][];
        };
        /** @description Serializer for DepartmentEducationalProgram. */
        DepartmentEducationalProgram: {
            readonly id: number;
            /** Код освітньої програми */
            code: string;
            readonly name: string;
            readonly description: string;
            readonly degree: string;
            readonly form: string;
            /** Duration (years) */
            duration?: number | null;
            /** Total ECTS credits */
            total_credits?: number | null;
            readonly bachelor: string;
            readonly magistracy: string;
            readonly postgraduate: string;
            readonly subject: components["schemas"]["CategorizedTag"][];
            readonly education_forms: components["schemas"]["CategorizedTag"][];
            readonly education_levels: components["schemas"]["CategorizedTag"][];
            readonly subjects: components["schemas"]["ProgramSubject"][];
        };
        /** @description Serializer for DepartmentHistory. */
        DepartmentHistory: {
            readonly id: number;
            readonly year: string;
            readonly text: string;
        };
        /** @description Serializer for DepartmentList. */
        DepartmentList: {
            readonly id: number;
            readonly name: string;
        };
        /** @description Serializer for EducationalProgram. */
        EducationalProgram: {
            readonly id: number;
            /** Код освітньої програми */
            code: string;
            readonly name: string;
            readonly subject: components["schemas"]["CategorizedTag"][];
            readonly education_forms: components["schemas"]["CategorizedTag"][];
            readonly education_levels: components["schemas"]["CategorizedTag"][];
        };
        /** @description Serializer for an Events objects */
        Events: {
            readonly id: number;
            readonly title: string;
            /** Слаг події */
            slug?: string;
            readonly body: string;
            readonly body_html: string;
            /**
             * Cover image
             * Format: uri
             */
            cover?: string | null;
            /** Format: date */
            event_date?: string | null;
            location?: string;
            category: components["schemas"]["EventsCategory"];
            /**
             * Дата створення
             * Format: date-time
             */
            readonly created_at: string;
            /**
             * Востаннє оновлено
             * Format: date-time
             */
            readonly updated_at: string;
        };
        /** @description Serializer for EventsCategory objects */
        EventsCategory: {
            readonly id: number;
            readonly name: string;
            /**
             * RGB значення
             * @description Необхідний колір RGBA у форматі (255,255,255,0.5) для дизайну на стороні клієнта
             */
            rgb_color: string;
        };
        /** @description Serializer for the FAQ model. */
        FAQ: {
            readonly id: number;
            readonly question: string;
            readonly answer: string;
        };
        /** @description Serializer for FacultyMember. */
        FacultyMember: {
            readonly id: number;
            readonly name: string;
            readonly role: string;
            readonly specialty: string;
            /**
             * Photo
             * Format: uri
             */
            image?: string;
            /** Format: email */
            email?: string;
            /** Аудиторія */
            audience?: string;
        };
        GoogleLoginRequestRequest: {
            /** @description Authorization code від Google */
            code: string;
            /** @description PKCE code verifier */
            code_verifier: string;
        };
        GoogleLoginResponse: {
            /** @description Bearer токен для запитів */
            access_token: string;
            /** @description Час дії токена в секундах */
            expires_in: number;
            /** @description Завжди "Bearer" */
            token_type: string;
        };
        /**
         * @description * `refresh_token` - refresh_token
         * @enum {string}
         */
        GrantTypeEnum: "refresh_token";
        /** @description Serializer for HeadOfDepartment. */
        HeadOfDepartment: {
            readonly id: number;
            readonly full_name: string;
            readonly regalia: string;
            /** Format: email */
            email?: string | null;
            /** Аудиторія */
            audience?: string | null;
        };
        /** @description Serializer for the MainSliderItem model. */
        MainSliderItem: {
            /**
             * Зображення слайдера
             * Format: uri
             */
            image: string;
        };
        /** @description Serializer for the Partners model. */
        Partners: {
            readonly id: number;
            readonly name: string;
            /**
             * Зображення слайдера
             * Format: uri
             */
            image: string;
            /** Format: uri */
            site_url: string;
        };
        /** @description Serializer for ProgramSubject. */
        ProgramSubject: {
            readonly id: number;
            readonly name: string;
            semester: number;
            /**
             * ECTS credits
             * Format: decimal
             */
            credits: string;
            /** Subject type */
            type?: components["schemas"]["TypeEnum"];
        };
        /**
         * @description * `AD` - AD
         *     * `TE` - TE
         *     * `ST` - ST
         *     * `DO` - DO
         *     * `GU` - GU
         * @enum {string}
         */
        RoleEnum: "AD" | "TE" | "ST" | "DO" | "GU";
        /** @description Serializer for the StatisticBlock model. */
        StatisticBlock: {
            readonly id: number;
            /**
             * Початкове значення
             * @description Початкове значення для правильної роботи анімацій
             */
            start_value?: number | null;
            /**
             * Елемент слайдера
             * @description Визначає в якому порядку будуть передаватись елементи
             */
            order: number;
            readonly title: string;
            readonly description: string;
        };
        TokenRefreshRequestRequest: {
            /** @description Завжди `refresh_token`
             *
             *     * `refresh_token` - refresh_token */
            grant_type: components["schemas"]["GrantTypeEnum"];
            /** @description OAuth2 client_id застосунку */
            client_id: string;
        };
        TokenRefreshResponse: {
            access_token: string;
            expires_in: number;
            token_type: string;
        };
        /**
         * @description * `MN` - Mandatory
         *     * `EL` - Elective
         * @enum {string}
         */
        TypeEnum: "MN" | "EL";
        UserProfileResponse: {
            id: number;
            first_name: string;
            last_name: string;
            /** Format: email */
            email: string;
            /** @description URL аватара з Google */
            avatar: string;
        };
        UserRoleResponse: {
            /** @description null для гостя */
            id: number | null;
            /** @description GU — неавторизований
             *
             *     * `AD` - AD
             *     * `TE` - TE
             *     * `ST` - ST
             *     * `DO` - DO
             *     * `GU` - GU */
            role: components["schemas"]["RoleEnum"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    v1_auth_google_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLoginRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["GoogleLoginRequestRequest"];
                "multipart/form-data": components["schemas"]["GoogleLoginRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleLoginResponse"];
                };
            };
            /** @description Відсутній code/code_verifier або помилка Google */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequestRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefreshResponse"];
                };
            };
            /** @description Невалідний або протермінований refresh_token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_core_alumni_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_core_alumni_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_core_alumni_slider_items_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlumniSlider"][];
                };
            };
        };
    };
    v1_core_alumni_years_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список років, наприклад: [2024, 2023, 2022] */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number;
                };
            };
        };
    };
    v1_core_educational_programs_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EducationalProgram"][];
                };
            };
        };
    };
    v1_core_faq_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FAQ"][];
                };
            };
        };
    };
    v1_core_main_slider_items_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MainSliderItem"][];
                };
            };
        };
    };
    v1_core_partners_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Partners"][];
                };
            };
        };
    };
    v1_core_statistic_block_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatisticBlock"][];
                };
            };
        };
    };
    v1_departments_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentList"][];
                };
            };
        };
    };
    v1_departments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentDetail"];
                };
            };
        };
    };
    v1_events_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Events"][];
                };
            };
        };
    };
    v1_events_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Events"];
                };
            };
        };
    };
    v1_users_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Токен відсутній або недійсний */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_users_role_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRoleResponse"];
                };
            };
        };
    };
}
