# Generated by Django 5.2.5 on 2025-08-17 07:30

import django.db.models.deletion
import parler.fields
import parler.models
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorizedTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('subject', 'Subject'), ('education_form', 'Form'), ('education_level', 'Education Level')], max_length=50)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'categorized_tag',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'Department',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EducationalProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Program code')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_program', to='departments.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Educational program',
                'verbose_name_plural': 'Educational programs',
                'db_table': 'EducationalProgram',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FormTaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('educational_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_items', to='departments.educationalprogram')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_items', to='departments.categorizedtag')),
            ],
            options={
                'verbose_name': 'Form Tag',
                'verbose_name_plural': 'Form Tags',
                'db_table': 'form_tag',
                'unique_together': {('educational_program', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='education_forms',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='departments.FormTaggedItem', to='departments.CategorizedTag', verbose_name='Education Forms'),
        ),
        migrations.CreateModel(
            name='HeadOfDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Head of the department email')),
                ('audience', models.CharField(blank=True, max_length=255, null=True, verbose_name='Audience')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_of_department', to='departments.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Head of Department',
                'verbose_name_plural': 'Head of Departments',
                'db_table': 'HeadOfDepartment',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LevelTaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('educational_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_items', to='departments.educationalprogram')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_items', to='departments.categorizedtag')),
            ],
            options={
                'verbose_name': 'Level Tag',
                'verbose_name_plural': 'Level Tags',
                'db_table': 'level_tag',
                'unique_together': {('educational_program', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='education_levels',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='departments.LevelTaggedItem', to='departments.CategorizedTag', verbose_name='Education Levels'),
        ),
        migrations.CreateModel(
            name='SubjectTaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('educational_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_items', to='departments.educationalprogram')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_items', to='departments.categorizedtag')),
            ],
            options={
                'verbose_name': 'Subject Tag',
                'verbose_name_plural': 'Subject Tags',
                'unique_together': {('educational_program', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='subject',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='departments.SubjectTaggedItem', to='departments.CategorizedTag', verbose_name='Subjects'),
        ),
        migrations.CreateModel(
            name='CategorizedTagTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='departments.categorizedtag')),
            ],
            options={
                'verbose_name': 'Tag Translation',
                'db_table': 'categorized_tag_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DepartmentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, verbose_name='Department name')),
                ('description', models.TextField(verbose_name='Department description')),
                ('address', models.CharField(max_length=255, verbose_name='Department address')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translated_fields', to='departments.department')),
            ],
            options={
                'verbose_name': 'Department Translation',
                'db_table': 'Department_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EducationalProgramTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, verbose_name='Educational program name')),
                ('description', models.TextField(verbose_name='Educational program description')),
                ('bachelor', models.JSONField(blank=True, help_text="Structure like: {'code': 'F1', 'specialty': '...', 'program': '...'}", null=True, verbose_name='Bachelor program structure')),
                ('magistracy', models.JSONField(blank=True, help_text="Structure like: {'code': 'F1', 'specialty': '...', 'program': '...'}", null=True, verbose_name='Magistracy program structure')),
                ('postgraduate', models.JSONField(blank=True, help_text="Structure like: {'code': 'F1', 'specialty': '...', 'program': '...'}", null=True, verbose_name='Postgraduate program structure')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translated_fields', to='departments.educationalprogram')),
            ],
            options={
                'verbose_name': 'Educational program Translation',
                'db_table': 'EducationalProgram_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HeadOfDepartmentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('regalia', models.CharField(help_text='Regalias head of the department', max_length=255, verbose_name='Regalia')),
                ('full_name', models.CharField(help_text='Full name of the head', max_length=255, verbose_name='Full name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translated_fields', to='departments.headofdepartment')),
            ],
            options={
                'verbose_name': 'Head of Department Translation',
                'db_table': 'HeadOfDepartment_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
