# Generated by Django 6.0.5 on 2026-05-22 14:24

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalprogram',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Duration (years)'),
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='total_credits',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Total ECTS credits'),
        ),
        migrations.AddField(
            model_name='educationalprogramtranslation',
            name='degree',
            field=models.CharField(blank=True, max_length=64, verbose_name='Degree'),
        ),
        migrations.AddField(
            model_name='educationalprogramtranslation',
            name='form',
            field=models.CharField(blank=True, max_length=128, verbose_name='Study form'),
        ),
        migrations.CreateModel(
            name='DepartmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='departments.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Department History Entry',
                'verbose_name_plural': 'Department History',
                'db_table': 'DepartmentHistory',
                'ordering': ['order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='faculty/', verbose_name='Photo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='departments.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Faculty Member',
                'verbose_name_plural': 'Faculty Members',
                'db_table': 'FacultyMember',
                'ordering': ['order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProgramSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(verbose_name='Semester')),
                ('credits', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='ECTS credits')),
                ('type', models.CharField(choices=[('MN', 'Mandatory'), ('EL', 'Elective')], default='MN', max_length=2, verbose_name='Subject type')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='departments.educationalprogram', verbose_name='Educational program')),
            ],
            options={
                'verbose_name': 'Program Subject',
                'verbose_name_plural': 'Program Subjects',
                'db_table': 'ProgramSubject',
                'ordering': ['semester', 'order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DepartmentHistoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('year', models.CharField(max_length=64, verbose_name='Year')),
                ('text', models.TextField(verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='departments.departmenthistory')),
            ],
            options={
                'verbose_name': 'Department History Entry Translation',
                'db_table': 'DepartmentHistory_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FacultyMemberTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, verbose_name='Full name')),
                ('role', models.CharField(max_length=255, verbose_name='Role')),
                ('specialty', models.CharField(max_length=255, verbose_name='Specialty')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='departments.facultymember')),
            ],
            options={
                'verbose_name': 'Faculty Member Translation',
                'db_table': 'FacultyMember_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProgramSubjectTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, verbose_name='Subject name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='departments.programsubject')),
            ],
            options={
                'verbose_name': 'Program Subject Translation',
                'db_table': 'ProgramSubject_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
