# Generated by Django 5.2.1 on 2025-07-17 14:43

import django.db.models.deletion
import parler.fields
import parler.models
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorizedTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FormTaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_items', to='departments.educationalprogram')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_items', to='departments.categorizedtag')),
            ],
            options={
                'unique_together': {('educational_program', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='education_forms',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='departments.FormTaggedItem', to='departments.CategorizedTag', verbose_name='Education Forms'),
        ),
        migrations.CreateModel(
            name='LevelTaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_items', to='departments.educationalprogram')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_items', to='departments.categorizedtag')),
            ],
            options={
                'unique_together': {('educational_program', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='education_levels',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='departments.LevelTaggedItem', to='departments.CategorizedTag', verbose_name='Education Levels'),
        ),
        migrations.CreateModel(
            name='SubjectTaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_items', to='departments.educationalprogram')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_items', to='departments.categorizedtag')),
            ],
            options={
                'unique_together': {('educational_program', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='subject',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='departments.SubjectTaggedItem', to='departments.CategorizedTag', verbose_name='Subjects'),
        ),
        migrations.CreateModel(
            name='CategorizedTagTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='departments.categorizedtag')),
            ],
            options={
                'verbose_name': 'categorized tag Translation',
                'db_table': 'departments_categorizedtag_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
