# Generated by Django 6.0.5 on 2026-05-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_educationalprogram_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, upload_to='departments/', verbose_name='Department photo'),
        ),
        migrations.AddField(
            model_name='department',
            name='room',
            field=models.CharField(blank=True, max_length=64, verbose_name='Room'),
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='budget_seats',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Budget seats'),
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='contract_seats',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Contract seats'),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='audience',
            field=models.CharField(blank=True, max_length=64, verbose_name='Audience'),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
    ]
