# Generated by Django 5.2.1 on 2025-07-17 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('departments', '0002_categorizedtag_formtaggeditem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtaggeditem',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formtaggeditem',
            name='object_id',
            field=models.IntegerField(db_index=True, default=1, verbose_name='object ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leveltaggeditem',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leveltaggeditem',
            name='object_id',
            field=models.IntegerField(db_index=True, default=1, verbose_name='object ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjecttaggeditem',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjecttaggeditem',
            name='object_id',
            field=models.IntegerField(db_index=True, default=1, verbose_name='object ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorizedtag',
            name='category',
            field=models.CharField(choices=[('subject', 'Subject'), ('education_form', 'Form'), ('education_level', 'Education Level')], max_length=50),
        ),
    ]
