# Generated by Django 6.0.5 on 2026-05-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_department_image_department_room_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='headofdepartmenttranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='headofdepartmenttranslation',
            name='master',
        ),
        migrations.AlterModelOptions(
            name='headofdepartment',
            options={'verbose_name': 'Head of Department', 'verbose_name_plural': 'Heads of Department'},
        ),
        migrations.AddField(
            model_name='facultymember',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Full name (EN)'),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='name_uk',
            field=models.CharField(default='', max_length=255, verbose_name='Full name (UK)'),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='role_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Role (EN)'),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='role_uk',
            field=models.CharField(default='', max_length=255, verbose_name='Role (UK)'),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='specialty_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Specialty (EN)'),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='specialty_uk',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Specialty (UK)'),
        ),
        migrations.AddField(
            model_name='headofdepartment',
            name='full_name_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Full name (EN)'),
        ),
        migrations.AddField(
            model_name='headofdepartment',
            name='full_name_uk',
            field=models.CharField(default='', max_length=255, verbose_name='Full name (UK)'),
        ),
        migrations.AddField(
            model_name='headofdepartment',
            name='regalia_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Regalia (EN)'),
        ),
        migrations.AddField(
            model_name='headofdepartment',
            name='regalia_uk',
            field=models.CharField(default='', max_length=255, verbose_name='Regalia (UK)'),
        ),
        migrations.AlterField(
            model_name='headofdepartment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.DeleteModel(
            name='FacultyMemberTranslation',
        ),
        migrations.DeleteModel(
            name='HeadOfDepartmentTranslation',
        ),
    ]
