# Generated by Django 5.2.1 on 2025-07-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_formtaggeditem_content_type_formtaggeditem_object_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorizedtag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='categorizedtagtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Tag Translation'},
        ),
        migrations.AlterModelOptions(
            name='formtaggeditem',
            options={'verbose_name': 'Form Tag', 'verbose_name_plural': 'Form Tags'},
        ),
        migrations.AlterModelOptions(
            name='leveltaggeditem',
            options={'verbose_name': 'Level Tag', 'verbose_name_plural': 'Level Tags'},
        ),
        migrations.AlterModelOptions(
            name='subjecttaggeditem',
            options={'verbose_name': 'Subject Tag', 'verbose_name_plural': 'Subject Tags'},
        ),
        migrations.AlterModelTable(
            name='categorizedtag',
            table='categorized_tag',
        ),
        migrations.AlterModelTable(
            name='categorizedtagtranslation',
            table='categorized_tag_translation',
        ),
        migrations.AlterModelTable(
            name='formtaggeditem',
            table='form_tag',
        ),
        migrations.AlterModelTable(
            name='leveltaggeditem',
            table='level_tag',
        ),
    ]
