# Generated by Django 6.0.5 on 2026-05-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_alter_headofdepartmenttranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headofdepartment',
            name='image',
            field=models.ImageField(blank=True, upload_to='head_of_department/', verbose_name='Photo'),
        ),
    ]
