# Generated by Django 6.0.5 on 2026-05-31 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_headofdepartment_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultymember',
            options={'verbose_name': 'Faculty Member', 'verbose_name_plural': 'Faculty Members'},
        ),
        migrations.RemoveField(
            model_name='facultymember',
            name='order',
        ),
    ]
