# Generated by Django 6.0.5 on 2026-05-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_alter_facultymember_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenthistory',
            name='image',
            field=models.ImageField(blank=True, upload_to='history/', verbose_name='Photo'),
        ),
    ]
