# Generated by Django 6.0.5 on 2026-05-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0007_departmenthistory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmenthistory',
            name='image',
        ),
        migrations.AddField(
            model_name='department',
            name='history_image',
            field=models.ImageField(blank=True, upload_to='departments/history/', verbose_name='History photo'),
        ),
    ]
