# Generated by Django 6.0.5 on 2026-05-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0008_remove_departmenthistory_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenthistory',
            name='text_en',
            field=models.TextField(blank=True, default='', verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='departmenthistory',
            name='text_uk',
            field=models.TextField(default='', verbose_name='Description (UK)'),
        ),
        migrations.AddField(
            model_name='departmenthistory',
            name='year_en',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Year (EN)'),
        ),
        migrations.AddField(
            model_name='departmenthistory',
            name='year_uk',
            field=models.CharField(default='', max_length=64, verbose_name='Year (UK)'),
        ),
        migrations.DeleteModel(
            name='DepartmentHistoryTranslation',
        ),
    ]
