# Generated by Django 6.0.5 on 2026-05-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0009_departmenthistory_text_en_departmenthistory_text_uk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmenthistory',
            name='year_en',
        ),
        migrations.RemoveField(
            model_name='departmenthistory',
            name='year_uk',
        ),
        migrations.AddField(
            model_name='departmenthistory',
            name='year',
            field=models.CharField(default='', max_length=64, verbose_name='Year'),
        ),
    ]
