# Generated by Django 6.0.5 on 2026-06-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0012_programsubject_control_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalprogram',
            name='url',
            field=models.URLField(blank=True, verbose_name='Program URL'),
        ),
    ]
