# Generated by Django 6.0.5 on 2026-06-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0013_educationalprogram_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymember',
            name='url',
            field=models.URLField(blank=True, verbose_name='Wiki URL'),
        ),
        migrations.AddField(
            model_name='headofdepartment',
            name='url',
            field=models.URLField(blank=True, verbose_name='Wiki URL'),
        ),
    ]
