# Generated by Django 6.0.5 on 2026-06-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0014_facultymember_url_headofdepartment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programsubject',
            name='semester',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Semester'),
        ),
    ]
