# Generated by Django 6.0.5 on 2026-06-13 12:34

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0016_remove_tags_and_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalprogramtranslation',
            name='description',
            field=mdeditor.fields.MDTextField(blank=True, default='', verbose_name='Educational program description'),
        ),
    ]
