# Generated by Django 6.0.5 on 2026-06-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0017_alter_educationalprogramtranslation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalprogramtranslation',
            name='name_op',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Educational program name'),
        ),
        migrations.AlterField(
            model_name='educationalprogramtranslation',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Specialty name'),
        ),
    ]
