# Generated by Django 6.0.5 on 2026-06-13 18:31

import core.utils
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0018_educationalprogramtranslation_name_op_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_uk', models.CharField(default='', max_length=255, verbose_name='Full name (UK)')),
                ('full_name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Full name (EN)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('image', models.ImageField(blank=True, upload_to=core.utils.UploadTo('institute_leaders'), verbose_name='Photo')),
                ('url', models.URLField(blank=True, verbose_name='Wiki URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Institute Leader',
                'verbose_name_plural': 'Institute Leaders',
                'db_table': 'InstituteLeader',
                'ordering': ['order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InstituteLeaderTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('position', models.CharField(max_length=255, verbose_name='Position')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translated_fields', to='departments.instituteleader')),
            ],
            options={
                'verbose_name': 'Institute Leader Translation',
                'db_table': 'InstituteLeader_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
