# Generated by Django 6.0.5 on 2026-06-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0021_alter_instituteleadermember_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituteleadership',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='instituteleadership',
            name='title_uk',
        ),
    ]
