# Generated by Django 6.0.5 on 2026-05-31 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0010_remove_departmenthistory_year_en_and_more'),
        ('users', '0002_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='departments.department', verbose_name='Department'),
        ),
    ]
