# Generated by Django 5.2.1 on 2025-07-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ST', 'Student'), ('TE', 'Teacher'), ('GU', 'Guest'), ('OP', 'Data Operator')], default='GU', max_length=2, verbose_name='Role'),
        ),
    ]
