# Generated by Django 5.2.1 on 2025-07-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ST', 'Student'), ('TE', 'Teacher'), ('OP', 'Data Operator')], default='ST', max_length=2, verbose_name='Role'),
        ),
    ]
