# Generated by Django 5.2.1 on 2025-06-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainSliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
            ],
            options={
                'verbose_name': 'Slider item',
                'verbose_name_plural': 'Slider items',
                'db_table': 'MainSliderItem',
            },
        ),
    ]
