# Generated by Django 5.2.5 on 2025-08-17 07:30

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='alumni-slider/')),
            ],
            options={
                'verbose_name': 'Alumni slider item',
                'verbose_name_plural': 'Alumni slider items',
                'db_table': 'AlumniSlider',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'db_table': 'FAQ',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MainSliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Slider image')),
            ],
            options={
                'verbose_name': 'Slider item',
                'verbose_name_plural': 'Slider items',
                'db_table': 'MainSliderItem',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partners/', verbose_name='Partner image')),
                ('site_link', models.URLField(help_text='Link to partner site', verbose_name='Site link')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'db_table': 'Partner',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StatisticBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_value', models.IntegerField(blank=True, help_text='Values for proper animation operation', null=True, verbose_name='Start value')),
                ('order', models.PositiveIntegerField(help_text='Determines yhe order in which elements will be passed', verbose_name='Order item')),
            ],
            options={
                'verbose_name': 'Statistic block item',
                'verbose_name_plural': 'Statistic block items',
                'db_table': 'StatistickBlock',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Alumnus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='alumnus/')),
                ('links', models.JSONField(blank=True, help_text="Structure like: {'instagram': 'link', 'telegram': 'link', 'facebook': 'link'}", null=True, verbose_name='Social links or other publication')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('date_of_graduation', models.DateField(verbose_name='Date of graduation')),
            ],
            options={
                'verbose_name': 'Alumnus',
                'verbose_name_plural': 'Alumni',
                'db_table': 'Alumnus',
                'ordering': ('-date_of_graduation',),
                'indexes': [models.Index(fields=['date_of_graduation'], name='Alumnus_date_of_371cc9_idx')],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AlumnusTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('text', models.TextField(blank=True, verbose_name='About student')),
                ('major', models.CharField(max_length=50, verbose_name='Major')),
                ('degree', models.CharField(max_length=50, verbose_name='Degree')),
                ('workplace', models.CharField(blank=True, max_length=255, verbose_name='Workplace')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Position')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.alumnus')),
            ],
            options={
                'verbose_name': 'Alumnus Translation',
                'db_table': 'Alumnus_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FAQTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', models.CharField(max_length=255, verbose_name='Answer')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.faq')),
            ],
            options={
                'verbose_name': 'FAQ Translation',
                'db_table': 'FAQ_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PartnerTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.partner')),
            ],
            options={
                'verbose_name': 'Partner Translation',
                'db_table': 'Partner_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StatisticBlockTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.statisticblock')),
            ],
            options={
                'verbose_name': 'Statistic block item Translation',
                'db_table': 'StatistickBlock_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
