# Generated by Django 5.2.1 on 2025-06-29 09:03

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_value', models.IntegerField(blank=True, help_text='Values for proper animation operation', null=True, verbose_name='Start value')),
            ],
            options={
                'verbose_name': 'Statistic block item',
                'verbose_name_plural': 'Statistic block items',
                'db_table': 'StatistickBlock',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='mainslideritem',
            name='image',
            field=models.ImageField(upload_to='banners/', verbose_name='Slider image'),
        ),
        migrations.CreateModel(
            name='StatisticBlockTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.statisticblock')),
            ],
            options={
                'verbose_name': 'Statistic block item Translation',
                'db_table': 'StatistickBlock_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
