# Generated by Django 5.2.5 on 2025-08-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnus',
            name='status',
            field=models.CharField(choices=[('PB', 'Published'), ('DF', 'Draft')], default='DF', max_length=2, verbose_name='Status'),
        ),
    ]
