# Generated by Django 5.2.1 on 2025-06-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_statisticblock_alter_mainslideritem_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticblock',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Determines yhe order in which elements will be passed', verbose_name='Order item'),
            preserve_default=False,
        ),
    ]
