# Generated by Django 6.0.5 on 2026-06-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alumnus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnus',
            name='image',
            field=models.ImageField(blank=True, upload_to='alumnus/'),
        ),
    ]
