# Generated by Django 5.2.1 on 2025-07-09 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_partners_partnerstranslation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partners',
            new_name='Partner',
        ),
        migrations.RenameModel(
            old_name='PartnersTranslation',
            new_name='PartnerTranslation',
        ),
    ]
