# Generated by Django 5.2.1 on 2025-07-21 09:02

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_faq_faqtranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='alumnus/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('date_of_graduation', models.DateField(verbose_name='Date of graduation')),
            ],
            options={
                'verbose_name': 'Alumnus',
                'verbose_name_plural': 'Alumni',
                'db_table': 'Alumnus',
                'ordering': ('-date_of_graduation',),
                'indexes': [models.Index(fields=['date_of_graduation'], name='Alumnus_date_of_371cc9_idx')],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AlumnusTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('text', models.TextField(blank=True, verbose_name='About student')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.alumnus')),
            ],
            options={
                'verbose_name': 'Alumnus Translation',
                'db_table': 'Alumnus_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
