# Generated by Django 5.2.1 on 2025-07-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alumnus_alumnustranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnus',
            name='links',
            field=models.JSONField(blank=True, help_text="Structure like: {'instagram': 'link', 'telegram': 'link', 'facebook': 'link'}", null=True, verbose_name='Social links or other publication'),
        ),
    ]
