# Generated by Django 5.2.1 on 2025-08-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alumnus_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='alumni-slider/')),
            ],
            options={
                'verbose_name': 'Alumni slider item',
                'verbose_name_plural': 'Alumni slider items',
                'db_table': 'AlumniSlider',
            },
        ),
    ]
