# Generated by Django 5.2.1 on 2025-08-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alumnislider'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnustranslation',
            name='degree',
            field=models.CharField(default='', max_length=50, verbose_name='Degree'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumnustranslation',
            name='major',
            field=models.CharField(default='', max_length=50, verbose_name='Major'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumnustranslation',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='alumnustranslation',
            name='workplace',
            field=models.CharField(blank=True, max_length=255, verbose_name='Workplace'),
        ),
    ]
